### ISSUE TITLE
Python Wrapper

### ISSUE THREAD

**Issue by webysther** [TPC-Council/HammerDB#108]
There's a [great python](https://github.com/cloud-bulldozer/snafu) decoupled from [ripsaw](https://github.com/cloud-bulldozer/ripsaw) to get result information of HammerDB and format to machine-readable format.

Looking the [wrapper code](https://github.com/cloud-bulldozer/snafu/blob/master/hammerdb/hammerd_wrapper.py) looks a little focus on ElasticSearch and I think to create a library on pip like:

```bash
pip install hammerdb
```

This library will use [docker version](https://github.com/TPC-Council/HammerDB/issues/107) (after creating a image with all drivers and driver specific database tag).

Thinking in this strategy, sounds good **provide a solution to get results in modern machine-readable format** like JSON, Parquet and Dataframe but XML, CSV.

This is better than parse a semi-structured result that can change without notice.

This is tottally different from https://github.com/TPC-Council/HammerDB/issues/17

Questions:

- There's a better way to get results?
- What is the thoughts about this ideia?
- What suggestions for this solution?

**Comment by sm-shaw** [comment]
As some initial thoughts there is a current way to get the output of HammerDB in JSON format using the HammerDB web service by running hammerdbws instead of hammerdbcli. Some details are here https://www.hammerdb.com/blog/uncategorized/using-hammerdb-as-a-web-service/. Using this the output is now decoupled so instead is stored in a SQLite database referenced by a job id and retrieved in JSON format. In theory it would be possible to do this in CLI mode as well if there was enough demand for it. 

For #17 definitely appreciate this is different - just to note for anyone following up on Python with HammerDB that adding Python to HammerDB for running workloads is straightforward however testing has shown Python performance to be very poor for performance testing. The reason is the single threaded nature of Python (GIL) even with multiple threads, so if multiple HammerDB virtual users create Python interpreters they can only ever run single threaded at the back end. Therefore for any workload that is performance critical the native TCL threading built into HammerDB definitely remains the way to go.

**Comment by webysther** [comment]
Yes, the wrapper make more sense because use the threading power of TCL and be reuse the job done and expands the use for another's structures and make possible to other scale.

As-a-webs-service sounds to big to a benchmark, sounds more powerful create multiple hammerdb docker container using python in a master machine creating a benchmark to multiple databases at same time. Ok, there's a lot of considerations here, but, I think this is a start point for a bright future. <3

**Comment by webysther** [comment]
I will work in something like this, if any change good or not I will update this issue.

**Comment by sm-shaw** [comment]
A newer python TCL integration package https://github.com/flightaware/tohil

**Comment by sm-shaw** [comment]
Python CLI interface was added in v4.6
