### ISSUE TITLE
Instream data compression

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#11]
Add instream zip and gzip options to compress data during creation (already TCL functions)

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov. 
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then a new issue can be reopened and self-assigned.
