### ISSUE TITLE
Please revert recent change - Reverse print out of metrics to put NOPM ahead of TPM

### ISSUE THREAD

**Issue by billramo** [TPC-Council/HammerDB#111]
The recent commit to change the metrics is likely to break code used to analyze results of the Log files.
See https://github.com/TPC-Council/HammerDB/commit/9fd10072b88d2e7f887ae616db6429278fdceff5
Please revert back to the old way.

Instead, please consider creating summary CSV files with the results instead as an output switch option. For example,

Rampup Start Time | Transaction Start Time | Transaction End Time | Virtual Users | TPM | NOPM
1/7/2020 20:01 | 1/7/2020 20:03 | 1/7/2020 20:06 | 3 | 53319 | 11591

This way, we have a much easier way to load the data into BI tools.
Thanks,
Bill

**Comment by sm-shaw** [comment]
For now nothing has changed in the current version however this was done for the next release particularly because of the changes introduced to the stored procedures by Pull Request #92. This will be a major evolution and will both impact performance and change the ratio between TPM and NOPM for some of the databases, therefore this change is to signify that NOPM is to be the primary metric but still keep reporting TPM as it is useful to match to database performance statistics. 

Neveretheless this highlights arguably a wider issue such as highlighted by Issue Python Wrapper #108. Up to now 3rd party parsing of HammerDB output has not been a development consideration however this highlights that maybe it should be. Consequently rather than reverting it should be considered if there is a better way to report the output to be machine readable. Hammerdbws already reports output into a SQLite database that can be extracted in JSON format - therefore it should be considered if there is preference for a consistent output format that will be future proof and prevent such occurences happening again going forward.

**Comment by sm-shaw** [comment]
v4.0 will include an option in the  generic.xml configuration file under benchmark/first_result. If set to NOPM it will print out the result in the way introduced by this change. If set to TPM it will print the results exactly the same as the previous way. Setting first_result to TPM should not then break any parsing of the output file.
