### ISSUE TITLE
MariaDB 10.3 Oracle Compatibility

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#16]
MariaDB 10.3 introduced Oracle compatible PL/SQL.  Update MySQL workload to include option to build stored procedures as MariaDB PL/SQL Oracle compatible.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.
