### ISSUE TITLE
Add SAP HANA as a new database

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#2]
From Steve's original HammerDB Development list.
SAP HANA : TPC-C and TPC- H workload for SAP HANA develop against Express edition https://go.sap.com/developer/topics/sap-hana-express.html.  (Note already have the code patch to switch to latest ODBC code for the workload and queries for HANA). SAP have had a version of HammerDB for HANA for a period of time so PoC is done and much code written.

**Comment by rhoxie21** [comment]
@abondvt89 - any update on this issue?

**Comment by abondvt89** [comment]
@rhoxie21 No update on this yet.  Will need to follow up to see if SAP might donate code.

**Comment by abondvt89** [comment]
@rhoxie21 It looks like SAP does not have any code that can be contributed here.  We will continue to track this issue as a potential candidate for addition in a future release.  It can be prioritized if someone can contribute work in this area.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.
