### ISSUE TITLE
Language Localization

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#20]
Explore TCL Localization Chinese Language  https://www.tcl.tk/doc/howto/i18n.html#summary /  https://wiki.tcl-lang.org/page/msgcat  (requires Chinese/English Developer)

**Comment by sm-shaw** [comment]
Local feedback advises this is not a high priority task as English only version is not a major barrier.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.
