### ISSUE TITLE
Add monitor user - TPC-H

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#24]
Add monitor user to TPC-H workload to generate performance reports

**Comment by sm-shaw** [comment]
Can also standardise performance metrics on geomean for TPC-H and report these in the output to move away from reference to QphH

if { $rowcount > 0 } { lappend qlist $value }
	      } 
set end [ clock seconds ]
set wall [ expr $end - $start ]
puts "Completed query set in $wall seconds"
puts "Geometric mean of query times returning rows is [ format \"%.5f\" [ gmean $qlist ]]"
oralogoff $lda

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.

Geomean has already been implemented to comply with TPC desire to move away from reference to QphH.
