### ISSUE TITLE
Add AWR report - Oracle

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#26]

**Comment by KJlt77** [comment]
Please have in mind not all Oracle customers have licences for using AWR. Please consider using AWR as an not mandatory option in HammerDB.

**Comment by sm-shaw** [comment]
This enhancement is not yet in development. Nevertheless as with the TPC-C workload, statspack is an alternative that can be easily modified from having AWR as a default. Therefore the approach will be AWR as the default but to ensure that statspack can be used instead (by some manual code changes) if preferred/required.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.
