### ISSUE TITLE
Add ref cursors and memory dump - Oracle

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#27]
HammerDB’s oldest feature is conversion and replay of Oracle Trace Files  http://houseofbrick.com/hammerdb-capture-and-replay-for-oracle/. Implement Oracle Ref Cursors and convert memory dumps in tracefile conversion.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.

Was partly implemented, but not completed.
