### ISSUE TITLE
Unable to create >2 warehouses with >2 VUs in TPC-C in MariaDB (v4.2 for Linux)

### ISSUE THREAD

**Issue by ckolovson** [TPC-Council/HammerDB#270]
Getting this error when trying to create 10 warehouses with 10 virtual users (VUs) on MariaDB for TPC-C build schema. Same error when trying to create 5 warehouses with 5 VUs. MariaDB server was running on SkySQL with 2 vCPUs and 8GB memory on AWS. So far, I have had success creating 1 warehouse with 1 virtual user and 2 warehouses w/ 2 VUs.
```
Unmatched Background Error - Invalid slave specification 
    while executing
"$notebook tab $index "
    (procedure "Detach" line 5)
    invoked from within
"Detach $w $state(drag_index)"
    (procedure "Release" line 12)
    invoked from within
"Release .ed_mainFrame.notebook 504 189 674 308"
    (command bound to event)
```

**Comment by sm-shaw** [comment]
HammerDB for MariaDB has been tested against multiple versions of 10.1, 10.2, 10.3, 10.4, 10.5 and 10.6 with 1000 warehouses per build and 64 virtual users, so there is not a reproducible issue with the MariaDB build. 

The error shown is a GUI error related to the detachable windows for the transaction counter and metrics - it is trying to detach a notebook tab it cannot find, so is not related to the MariaDB build. This is most likely when running the GUI over a high latency connection rather than locally. Some GUI options are to run the GUI over VNC (it is also possible to run the GUI in the cloud via a browser as well), or to set the GUI to run in fixed rather than scalable UHD mode. Alternatively, you can use the command line that does not require the GUI.

**Comment by ckolovson** [comment]
Thanks!!
