### ISSUE TITLE
Convert binlog into replay format - MySQL

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#29]
Explore conversion of MySQL statement binlog into replay format.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.
