### ISSUE TITLE
Oracle 21c with default container database

### ISSUE THREAD

**Issue by nandoverona** [TPC-Council/HammerDB#432]
### Discussed in https://github.com/TPC-Council/HammerDB/discussions/330

Hi Steve,

As a follow-up, the major problem in this discussion is that Oracle doesn't allow the normal syntax to create a user in a CDB.

Connected in the CDB: "create user TPCC identified by xxx;" will fail ORA-65096.

I'm using Hammerdb in a automated fashion, so in this context I let hammerdb to perform all steps, like Create Database, CreateUser, CreateSchema, etc. All older version working fine but not in 21c where Oracle implemented this restriction.

While troubleshooting I found an workaround for this, setting _ORACLE_SCRIPT to true. Below commands will work and create the user in the CDB. Oracle Doc ID 2148774.1 and Doc ID 2125233.1

```
alter session set "_ORACLE_SCRIPT"=true;  
create user TPCC identified by xxx; 
```

Do you think this is something possible to implement [here](https://github.com/TPC-Council/HammerDB/blob/master/src/oracle/oraoltp.tcl#L923)

Or the best option is to create a PDB and use this PDB in the HammerDB test? Of course this should be automated also in my case.

Thank you,

Luiz Verona
AWS

**Comment by sm-shaw** [comment]
It looks like the key difference between 21c and previous releases is that Oracle 21c  is multitenant only, so you can't have an install without a container database.  This means you should not be creating a user schema in the container database and should be creating a PDB first for the HammerDB install and it looks like the default license includes up to 3 PDBs. Therefore, it seems likely that "ORA-65096: invalid common user or role name" has been introduced when trying to create a user schema in the CDB because of this architectural and licence change so you have to create a PDB first when using 21c as the previous concept of a non CDB install is no longer permitted. More information is here https://docs.oracle.com/en/database/oracle/oracle-database/21/cncpt/CDBs-and-PDBs.html. 

So when you say:
>> Or the best option is to create a PDB and use this PDB in the HammerDB test?

For HammerDB running on Oracle 21c, yes you should create a PDB first. This is an Oracle change rather than a HammerDB one, but as #330 shows once you have done this then the workload will run fine.

**Comment by nandoverona** [comment]
Hi Steve.

Thank you for sharing your opinion on this one. Long term solution would be working in a PDB as Oracle probably can remove this hidden parameter anytime.
