### ISSUE TITLE
hammerdbcli auto script.tcl - Not Exists

### ISSUE THREAD

**Issue by dineshtessell** [TPC-Council/HammerDB#472]
Hi Team,

Thanks for the HammerDB benchmark tool, and its great.

As part of exploring the `HammerDB`, we found an issue where the `hammerdbcli` is going to hang.

We tested this functionality, by shutting down the PostgreSQL instance.

Then ran the `hammerdbcli` as like below.

```
$ ./hammerdbcli auto pgschema.tcl
HammerDB CLI v4.6
Copyright (C) 2003-2022 Steve Shaw
Type "help" for a list of commands
Initialized SQLite on-disk database /tmp/hammer.DB using existing tables (430,080 KB)
Database set to PostgreSQL
Benchmark set to TPC-C for PostgreSQL
Value disable for connection:pg_sslmode is the same as existing value disable, no change made
Script cleared
Deleting schema with 1 Virtual User
Do you want to delete the TPCC TPROC-C schema and role TPCC
 in host LOCALHOST:5432 under user POSTGRES?
Enter yes or no: replied yes
Vuser 1 created - WAIT IDLE
Vuser 1:RUNNING
Vuser 1:Connection to database failed connection to server at localhost (127.0.0.1), port 5432 failed: Connection refused Is the server running on that host and accepting TCP/IP connections? connection to server at localhost (::1), port 5432 failed: Cannot assign requested address Is the server running on that host and accepting TCP/IP connections?
Vuser 1:FINISHED FAILED
ALL VIRTUAL USERS COMPLETE
vudestroy success

...
...
...


^C
```

pgschema.tcl as below

`
$ cat pgschema.tcl
dbset db pg
dbset bm TPC-C
diset connection pg_sslmode disable

deleteschema
vudestroy

vuset logtotemp 1
diset tpcc pg_storedprocs true
diset tpcc pg_count_ware 4
diset tpcc pg_num_vu 1
diset tpcc pg_raiseerror true
buildschema
quit
`

Would you please let us know if we miss anything here. If postgresql is up and running, then the schema creation is successful, 
and the script exit status is as 0, but it is not the case when postgresql is shutdown.

Please let me know if i miss anything here.

Thanks

**Comment by sm-shaw** [comment]
Hi, 
Yes, so this is a minor bug I'm already aware of, however it is more of an inconvenience because as you point out that script has to fail to enter this state and you can Ctrl-C out of it. Also, it has to fail quickly making it an edge case so for example if you increase the vu count to build the schema you will find it won't happen. 
The cause is that the waittocomplete and runtimer functions that were automated in v4.6 and triggered automatically depends on having an event loop that exits when a variable is set.  In normal scenarios this works fine, however in the case you raise we have 1 vu and the database is down, so it runs so quickly it fails before it enters the event loop, Once it is in the loop of course the variable doesn't get set because it has already been set previously so it waits forever. 
Note that in the case you do set a higher VU count than 1 for the build, the additional VUs will show "Waiting for Monitor Thread" for a period of time before failing, so this is expected behaviour. 
Since you raise it as an Issue I will put in a PR to exit correctly in case of this scenario.

**Comment by dineshtessell** [comment]
Thank you for the quick response @sm-shaw.
HammerDB is amazing tool, and thank you so much
