### ISSUE TITLE
Release 4.5 broke compatibility with Babelfish for PostgreSQL

### ISSUE THREAD

**Issue by Alex-Zarenin** [TPC-Council/HammerDB#490]
Pull request https://github.com/TPC-Council/HammerDB/pull/372 made changes to HammerDB stored procedures for SQL Server introducing "SELECT TOP 50 PERCENT" clause, which made it incompatible with Babelfish.

Babelfish for PostgreSQL is an open-source project (https://github.com/babelfish-for-postgresql) that adds a Microsoft SQL Server-compatible end-point to PostgreSQL. Babelfish allows PostgreSQL to understand T-SQL, SQL Server’s proprietary SQL dialect, and supports the TDS communication protocol, so applications originally written for SQL Server may work with PostgreSQL with fewer code changes and without changing database drivers.

As HammerDB does not offer Babelfish as a separate target, for testing Babelfish performance we were using SQL Server target, which recent change made impossible due to Babelfish (at present) does not support "SELECT x PERCENT" where  x<> 100.

Please consider changing affected stored procedures to eliminate "SELECT 50 PERCENT" clause in favor of some alternative.

**Comment by sm-shaw** [comment]
As Babelfish provides SQL Server compatibility for PostgreSQL and this is legitimate SQL Server syntax it is probably better to open an Issue with babelfish to add support for "SELECT TOP X PERCENT" rather than modifiying the HammerDB SQL Server stored procedures to be compatible with the compatability layer. 
HammerDB already supports PostgreSQL natively so it would be better to run this version to test PostgreSQL rather than a SQL Server based one so we don't compromise by working around and not using features that SQL Server has but Babelfish doesn't.

**Comment by Alex-Zarenin** [comment]
Steve, thank you very much for your reply! Could you elaborate what benefits were expected by changing stored procedures to use  "SELECT TOP X PERCENT" versus previous SP format? Can NOPM results obtained using HammerDB 4.4 (using stored procedures without this clause) match NOPM results using latest HammerDB version?

**Comment by sm-shaw** [comment]
The reason for the changes are described in here https://github.com/TPC-Council/HammerDB/issues/371 and from this white paper https://www.principledtechnologies.com/Amazon/EC2-R5b-OLTP-competitive-science-0321-v2.pdf

The key reason was this section:

_Optimizing the database: Amazon Web Services (AWS) provided us with a script that modified the base TPC-C-like database. The script altered some row and page locking settings and modified some stored procedures to improve (N)OPM results for any solution running the benchmark._

So the overall goal was to use these Principled Technologies/AWS provided modifications and these were evaluated as described in the Issue. This meant everyone was using the same version of the SQL Server workload without needing to modify it. The individual statements themselves were not evaluated, it was the performance overall as a result from the changes and these were found to be positive. This was then reviewed and approved by the TPC-OSS subcommittee as a whole before being included. Therefore the question around "SELECT TOP X PERCENT" in particular is best directed to AWS using the white paper as a reference. 

There are no current plans to modify the stored procedures from what we have.  The best route to start with would be to look to improve Babelfish compatibility to support "SELECT TOP X PERCENT" rather than modify HammerDB and it looks like a lot of this conversation could take place within AWS.

**Comment by sm-shaw** [comment]
Closed as no further input and no current plans for updates to be compatible with Babelfish.
