### ISSUE TITLE
Running HammerDB DockerFile-built container in any K8s distro is failing

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#495]
### Discussed in https://github.com/TPC-Council/HammerDB/discussions/493

<div type='discussions-op-text'>

<sup>Originally posted by **rfsonders** January 23, 2023</sup>
Hi folks.
I am attempting, without success, to run the Dockerfile-built container, deployed to any K8s distro. Even testing with the small k8s docker desktop distro. The container loops with CrashLoopBackOff. Over and over. Also tested with AKS. Same error.

The container does run fine, directly in docker. I can bash right in and execute .tcl, not a problem.
I am at a loss as to why the same container will not start in k8s.

Any help, thoughts, or direction would be appreciated.
Thank you!
</div>

**Comment by rfsonders** [comment]
Hello. 
Some workarounds can be.
1. at the end of the DockerFile. CMD tail -f /dev/null
2. In the .yaml 
command: 
      - "sleep"
      - "604800"

I am still testing as to which is a better option.

**Comment by pooja-jain-17** [comment]
Hello Robert,  Thanks for pointing this out. 

As I understand, the HammerDB docker container immediately exits as we spin it **without the interactive options (-it)** 
For example if we run as 
       `docker run --name hammerdb hammerdb-v4.6`
instead of 
       `docker run -it --name hammerdb hammerdb-v4.6 bash`
Which is what I suspect is leading to CrashLoopbackoff on K8s. 

I liked your suggestion of adding sleep infinity to the yaml. I have tried and I think that it works fine.
Here is a snippet of the yaml.
```
apiVersion: v1
kind: Pod
metadata:
  name: hammerdb
spec:
  containers:
  - name: testpod
    image: tpcorg/hammerdb:latest
    command: ["sleep", "infinity"]

```

About the other suggestion, adding "CMD tail -f /dev/null" in the Dockerfile, This works too, but this may lead to Docker hangs or rogue containers running in background. I am not too sure about including this in the Dockerfile for now. 

Thanks.
