### ISSUE TITLE
Add BCP based load to TPROC-H Schema for SQL Server

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#593]
Pull Requests #587 and #592 have added a BCP based load to the TPROC-C schema that improves loading performance. The same approach could be added to the TPROC-H schema to also improve performance there, using these pull requests as a template for the changes that need to be added.

**Comment by JoshInnis** [comment]
Hello,

I work on the same team as [Krithika Satish](https://github.com/krithikasatish) and I am using those PRs as templates to alter the TPROC-H loading performance.

The template from those PRs are working well for this load process to with one issue. The address field for the supplier and customer tables is created with this command: `set address [ V_STR 25 ]`

This command will allow addresses to be created with commas in it. Which causes issues with BCP. The current solution we have is to run the command: `regsub -all "," $address " " address` Which replaces the commas with spaces. This logic currently only runs when the BCP logic is run.

**Comment by JoshInnis** [comment]
Would it make sense instead to use pipes '|' for all temporary files in the TPCH load? That would simplify the codebase a little bit.

**Comment by JoshInnis** [comment]
The bcp utility has some restrictions to date formatting that are causing an issue. The function `mk_time `in tpchcommon-1.0.tm formats dates with the three-letter abbreviation of the month, i.e.. 2023-SEP-14. However, in testing, BCP requires the numbered syntax: 2023-09-14, otherwise a parsing error is thrown. 

Currently I made a copy on the function `mk_time` called `mk_time_bcp` that makes the necessary alteration for BCP (TPCC uses datetime in its tables, whereas TPCH uses date, which is why this issue didn't appear earlier). 

If this is an adequate solution, does this new function belong in tpchcommon-1.0.tm or in mssqlsolap.tcl as this is the only place in the codebase where this function is needed?

**Comment by sm-shaw** [comment]
> Would it make sense instead to use pipes '|' for all temporary files in the TPCH load? That would simplify the codebase a little bit.

Yes, certainly if this is easier for you, then you can use a pipe delimiter for TPROC-H. A comma was only used as that is what was used for the TPROC-C BCP build.

**Comment by sm-shaw** [comment]
> Currently I made a copy on the function `mk_time` called `mk_time_bcp` that makes the necessary alteration for BCP (TPCC uses datetime in its tables, whereas TPCH uses date, which is why this issue didn't appear earlier).
> 
> If this is an adequate solution, does this new function belong in tpchcommon-1.0.tm or in mssqlsolap.tcl as this is the only place in the codebase where this function is needed?

Good question and solution. Let's keep it in tpchcommon-1.0.tm so it is next to the original function for reference and maybe just add a very brief comment above why it is needed for a reminder in future.
