### ISSUE TITLE
Memory consumption increasing running hammerdbcli on Windows

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#765]
### Discussed in https://github.com/TPC-Council/HammerDB/discussions/763

<div type='discussions-op-text'>

<sup>Originally posted by **filiptanic98** October 30, 2024</sup>
Hello all,

I noticed that memory consumption is constantly increasing when running HammerDB TPCC benchmarks through hammerdbcli and using .tcl scripts.
My infrastructure consists of containers created inside of Azure VMs. From those containers I am targeting my MS SQL Server instance.
To run hammerdb from containers I use .tcl scripts and hammerdbcli.
I noticed that sometimes when I run TPCC I was getting out of memory errors in containers.
After that I investigated and found out it was correlated with the benchmark duration.
I continued my investigation and found out that memory usage of tclsh86t process is constantly increasing when benchmark is running.
I also tried reproducing this from outside container on my local machine and behavior is same.
I tried with running HammerDB from GUI (which runs wish86t.exe process) and there is no memory usage increase.
Image1 - reproduced issue on my local machine:
![image](https://github.com/user-attachments/assets/db9bef46-790e-4779-8a90-14a1a44dc1a4)

Image2 - shows constant memory increase for the container running inside kubectl environment:
![image](https://github.com/user-attachments/assets/b3d7801d-7b8b-4970-bb35-718f70e8f50a)

Did someone encounter similar issues with hammerdbcli?</div>

**Comment by sm-shaw** [comment]
I have done an initial investigation and the effect can be observed on all databases on both Linux and Windows with both GUI and CLI. 

The cause is from the xtprof time profiling package, and therefore the increase in memory is to be expected. 

Every time a stored procedure is called for every virtual user, the timing data is recorded in a virtual user independent array. When each virtual user is finished, the data is shared with the monitor virtual user that collects all the timing data and reports it. 

The gathered data is deleted for each virtual user after sharing it, however some of the monitor virtual user dicts and thread shared variables are only reset on the next run. Therefore, we can free some memory by freeing these thread shared variables and dicts after the timings are reported, rather than at the start of a run. 

However, the main memory increase during a run can be explained by HammerDB gathering the timings for every VU for every function call and storing it locally in an array, which is a relatively large amount of data. 

Note that if the xtprof timer is not loaded (in the GUI or CLI) then timings are not gathered and there is no memory increase.

**Comment by mdcallag** [comment]
Can there be a way to avoid this memory growth? From tests with VU=1 and VU=8 I see RSS grow for hammerdbcli by about 0.3  KB per TPM x minute. For 60 minutes at 1M TPM the RSS grows by ~17GB from:
    ((60 * 1000000) * 0.3) / (1024 * 1024.0) == 17.166

With respect to workarounds, is it feasible to use a response time histogram, so the array size is fixed and small (maybe less than 100 buckets)?

The RSS growth makes it hard or impossible to run for hours and I want to do that in some cases when searching for perf bugs. One example is a DBMS with cyclic IO behavior (vacuum in Postgres, compaction in MyRocks) where those cycles might take an hour or longer to repeat.

And if it won't be fixed, this should be explained in the docs to avoid people who get confused when there are failures, as they might not be used to looking for signs that the OOM-killer arrived (via /var/log/messages or dmesg). And when the OOM-killer does arrive for me, it kills the DBMS processes. At first glance, I though there was a crash bug, but the real problem was OOM.

**Comment by sm-shaw** [comment]
Many thanks for the update.  Yes the response time metrics have evolved over time. The initial implementation only gathered the data from one Virtual User. Now with the the xtprof package this was extended to capture the data from all Virtual Users, this is fine for shorter runs but as you say is an issue for longer runs with a higher VU count and system performance is increasing all the time.
Also we ship all of the data to the main thread when the run is complete to calculate the percentiles. So there is potential to improve this. 
The most minimal straightforward change would be to move to a reservoir sampling based approach, so we are not capturing all of the data. Potentially later a HdrHistogram could be used if needed. 
We also have this issue open to extend the response time metrics by adding additional percentiles
https://github.com/TPC-Council/HammerDB/issues/831 so I will a reference to this issue there and plan to update both together.
