### ISSUE TITLE
Benchmark fails when configuring more than 1 iteration

### ISSUE THREAD

**Issue by peterschen** [TPC-Council/HammerDB#770]
**Guidance**
Bug reports are for when HammerDB is not behaving as expected.
Bug reports should not be submitted for help in understanding database performance related questions.
General questions on database performance or HammerDB usability should be submitted under Discussions.

**Describe the bug**
When launching a benchmark against Microsoft SQL Server (haven't tested other databases) with more than one iteration configured after the first iteration the test errors out with this error: `Error: Connection to DRIVER=ODBC Driver 18 for SQL Server;SERVER=tcp:sql-0,1433;TRUSTED_CONNECTION=YES;ENCRYPT=yes;TRUSTSERVERCERTIFICATE=yes could not be established : can't create object "odbc": command already exists with that name`.

First encountered with my CLI script but confirmed with a GUI driven benchmark which show the same behavior.

**To Reproduce**
Use the following script to reproduce the behavior:

```tcl
#!/bin/tclsh

set tmpdir `$::env(TMP)
dbset db mssqls
dbset bm TPC-C

diset connection mssqls_tcp true
diset connection mssqls_port 1433
diset connection mssqls_azure false
diset connection mssqls_encrypt_connection true
diset connection mssqls_trust_server_cert true
diset connection mssqls_authentication windows
diset connection mssqls_server {sql}

diset tpcc mssqls_dbase tpcc
diset tpcc mssqls_driver timed
diset tpcc mssqls_total_iterations 10000000
diset tpcc mssqls_rampup 2
diset tpcc mssqls_duration 1
diset tpcc mssqls_checkpoint true
diset tpcc mssqls_timeprofile true
diset tpcc mssqls_allwarehouse false
diset tpcc mssqls_count_ware 50

tcset refreshrate 2

vuset delay 150
vuset repeat 50
vuset iterations 5

loadscript
vuset vu 5  
vucreate
tcstart
vurun
vudestroy
tcstop
```

**Expected behavior**
Test repeated N times (N= iterations) instead of failing after the first iteration.

**Screenshots**
![image](https://github.com/user-attachments/assets/e12ae219-f557-425e-aba9-ba9dfc18b26b)
![image](https://github.com/user-attachments/assets/0ef59a63-30dc-46f0-8d3c-6ae7a760de1f)

**HammerDB Version (please complete the following information):**
 - Version: 4.12.
 - Build: Release download

**HammerDB Interface (please complete the following information):**
 - UI: CLI, GUI

**Operating System (please complete the following information):**
 - Server OS: Windows Server 2022
 - Client OS: Windows Server 2022

**Database Server (please complete the following information):**
 - Database name: Microsoft SQL Server
 - Database Release Version : 2022 (160)

**Database Client (please complete the following information):**
 - Database client name: ODBC Driver 18 for SQL Server

**Comment by sm-shaw** [comment]
Yes, so what is happening here is that the iterations setting can be seen as an outer loop around the internal iterations setting, i.e. the Total transactions per User setting in the Driver Options. In this case, the value is left at the long-running default, so the script is terminated before it reaches the last line which is odbc close, so when it is closed and then re-run the odbc connection still exists, hence the error. 

The intended use is (for both test and timed) set the Total transactions per User setting to a lower value, then odbc close will be reached, and the active virtual user will reconnect without error, as per the example below: 

![iterate1](https://github.com/user-attachments/assets/c6b2e032-018c-49e4-b14c-289d3c33c014)

But if you want to have the timed version terminate the virtual users and then have them reconnect, you can close the connection if it exists by adding the following at the start. 
```
#!/usr/local/bin/tclsh8.6
#EDITABLE OPTIONS##################################################
catch {odbc close};
set library tdbc::odbc ;# SQL Server Library
...
```

Note, however, once it reaches the timed period all virtual users will error on the first run because the run has been terminated since the timeout has been reached, so every subsequent run is going to see that the timeout has been reached on the first try and then exit. 

So, you also want the monitor virtual user to reset the timeout as follows:
```
switch $myposition {
   1 { 
if { [ tsv::get application abort ] } {  tsv::set application abort 0 } 
```

With these 2 small changes added, the workload will continue to iterate through a number of timed tests, which is probably more what you are trying to do, however you can also run multiple tests back to back with autopilot in the GUI or scripts with the CLI. 

![image](https://github.com/user-attachments/assets/165d9d17-4340-4374-96d9-5b44c61731f1)

I am not convinced this is a bug per se as it works when used as intended, i.e. an outer loop of Iterations around an inner loop of Total transactions per User, and can easily be modified as above. 

However, further information on the use case would be useful to evaluate any potential changes we may want to make to make this feature clearer.

**Comment by peterschen** [comment]
@sm-shaw Thank you for your quick and detailed reaction. I had thought this to be the case and worked around this by doing this:

```tcl
#!/bin/tclsh

set tmpdir `$::env(TMP)
dbset db mssqls
dbset bm TPC-C

diset connection mssqls_tcp true
diset connection mssqls_port 1433
diset connection mssqls_azure false
diset connection mssqls_encrypt_connection true
diset connection mssqls_trust_server_cert true
diset connection mssqls_authentication windows
diset connection mssqls_server {sql}

diset tpcc mssqls_dbase tpcc
diset tpcc mssqls_driver timed
diset tpcc mssqls_total_iterations 10000000
diset tpcc mssqls_rampup 2
diset tpcc mssqls_duration 1
diset tpcc mssqls_checkpoint true
diset tpcc mssqls_timeprofile true
diset tpcc mssqls_allwarehouse false
diset tpcc mssqls_count_ware 50

tcset refreshrate 2

vuset delay 150
vuset repeat 50

loadscript
vuset vu 5  
vucreate
tcstart

for {set i 0} {`$i < 6} {incr i} {
    vurun
}

vudestroy
tcstop
```
